apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - appProject.yaml
  - ./applications/victorialogs
  - ./applications/gatus
  # - ./applications/tempo
  # - ./applications/alloy
