apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind-jaeger
  namespace: argocd
spec:
  destination:
    namespace: jaeger
    server: https://kubernetes.default.svc
  project: observability
  source:
    path: overlays/kind
    repoURL: https://github.com/Vail-X/project-jaeger
    targetRevision: main
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
