apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind-kube-prometheus-stack
  namespace: argocd
spec:
  destination:
    namespace: vm
    server: https://kubernetes.default.svc
  project: observability
  source:
    path: overlays/kind
    repoURL: https://github.com/Vail-X/project-prometheus
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
