apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind-alloy
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: observability
  source:
    path: overlays/kind
    repoURL: https://github.com/Vail-X/project-alloy
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
