apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../appprojects/argocd
  - ../appprojects/observability
  - ../appprojects/projectapplication
  - ../appprojects/kube-prometheus-stack

helmGlobals:
  chartHome: ../../../charts
helmCharts:
  - name: argo-cd-9.0.4
    releaseName: argocd
    valuesFile: values.yaml
    namespace: argocd
